### PR TITLE
Report last known location when engine enabled

### LINKED ISSUE #141: FusedLocationApi won't send initial location
### Description
Okay, I am not completely sure if this is a bug or if I am using it wrong. I make a location request with a high smallest displacement while no last location is known (to LOST's FusedLocationApi). Then, I get no call to `onLocationChanged` as long as I do not move at least the given displacement first (and/or wait the interval, I did not test that).
However, I would expect that I get first **one** call to `onLocationChanged` regardless of the `smallestDisplacement` and `interval` since _no previous location was known_.

### Steps to Reproduce
1. I.e. using the code below
2. Have never before used the application, so that `getLastLocation` will return null
3. Make a location request (see below) with a high smallest displacement and/or a high interval
4. Witness that `onLocationChanged` not called. After I move for 1000m, then finally I get a call to `onLocationChanged`. (Tested only in the emulator)
```
LocationRequest request = LocationRequest.create()
		.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
		.setSmallestDisplacement(1000)
		.setInterval(5*60*1000); // 5 minutes

Location location = LocationServices.FusedLocationApi.getLastLocation(lostApiClient);
if(location != null)
{
	this.onLocationChanged(location);
}

LocationServices.FusedLocationApi.requestLocationUpdates(lostApiClient, request, this);
```

### Lost & Android Version
2.1.1 on Android 6.0

### PR DESCRIPTION
**Pull request by sarahlensing**
### Overview
This PR updates the `FusionEngine` to check for a last known location for each enabled location provider and return that location if it exists.

### Proposed Changes
Here is example output from these two test classes used

FusedLocationActivity
```
12-06 15:53:11.558 1765-1765/com.mapzen.googleplayservicestest D/Test: onConnected
12-06 15:53:11.568 1765-1765/com.mapzen.googleplayservicestest D/Test: last known network
12-06 15:53:11.568 1765-1765/com.mapzen.googleplayservicestest D/Test: ch acc:2198.0 lat:40.0173948 lng:-105.3028802 provider:network bearing:0.0 nanos:6514803000000 speed:0.0 time:1481064657644
12-06 15:53:11.568 1765-1765/com.mapzen.googleplayservicestest D/Test: lastKnownLocation
12-06 15:53:11.568 1765-1765/com.mapzen.googleplayservicestest D/Test: ch acc:2198.0 lat:40.0173948 lng:-105.3028802 provider:fused bearing:0.0 nanos:6648737000000 speed:0.0 time:1481064791578
12-06 15:53:11.578 1765-1765/com.mapzen.googleplayservicestest D/Test: Location Changed
12-06 15:53:11.578 1765-1765/com.mapzen.googleplayservicestest D/Test: ch acc:2198.0 lat:40.0173948 lng:-105.3028802 provider:fused bearing:0.0 nanos:6648746000000 speed:0.0 time:1481064791587
```

LostFusedLocationActivity
```
12-06 15:50:57.598 30873-30873/com.mapzen.googleplayservicestest D/Test: onConnected
12-06 15:50:57.598 30873-30873/com.mapzen.googleplayservicestest D/Test: last known network
12-06 15:50:57.598 30873-30873/com.mapzen.googleplayservicestest D/Test: ch acc:2198.0 lat:40.0173948 lng:-105.3028802 provider:network bearing:0.0 nanos:6477295000000 speed:0.0 time:1481064620137
12-06 15:50:57.598 30873-30873/com.mapzen.googleplayservicestest D/Test: lastKnownLocation
12-06 15:50:57.598 30873-30873/com.mapzen.googleplayservicestest D/Test: ch acc:2198.0 lat:40.0173948 lng:-105.3028802 provider:network bearing:0.0 nanos:6477295000000 speed:0.0 time:1481064620137
12-06 15:50:57.608 30873-30873/com.mapzen.googleplayservicestest D/Test: Location Changed
12-06 15:50:57.608 30873-30873/com.mapzen.googleplayservicestest D/Test: ch acc:2198.0 lat:40.0173948 lng:-105.3028802 provider:network bearing:0.0 nanos:6477295000000 speed:0.0 time:1481064620137
```

[FusedLocationActivity.txt](https://github.com/mapzen/lost/files/635268/FusedLocationActivity.txt)
[LostFusedLocationActivity.txt](https://github.com/mapzen/lost/files/635269/LostFusedLocationActivity.txt)

Closes #141

### CODE REVIEW

File: lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java [hunk 1]
```diff
@@ -144,6 +147,25 @@ private void enablePassive(long interval) throws SecurityException {
...
+
+  private void checkLastKnownNetwork() {
+    checkLastKnownAndNotify(NETWORK_PROVIDER);
+  }
+
+  private void checkLastKnownPassive() {
+    checkLastKnownAndNotify(PASSIVE_PROVIDER);
+  }
+
+  private void checkLastKnownAndNotify(String provider) {
```
Comment (ecgreb) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java]: For location requests with `PRIORITY_HIGH_ACCURACY` this method would be invoked for both `GPS_PROVIDER` and `NETWORK_PROVIDER` resulting in two initial location updates.

We should only send one initial location update and use the logic in `FusionEngine.getLastLocation()` to decide which one is best.
