### PR TITLE
Log Exceptions

### LINKED ISSUE #218: DeadObjectException with SNAPSHOT 3.0.1
We hit a DeadObjectException using the following SNAPSHOT 
> com.mapzen.android:lost:3.0.1-20170607.212149-4

Sadly we don't have a reprodicible use-case. Will update the ticket if we have more information. 

```
9: 32: 05.801 10677 - 10677 / com.mapbox.mapboxsdk.testapp: lost E / AndroidRuntime: FATAL EXCEPTION: main
Process: com.mapbox.mapboxsdk.testapp: lost, PID: 10677
java.lang.RuntimeException: android.os.DeadObjectException
at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(FusedLocationProviderServiceDelegate.java: 78)
at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java: 196)
at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java: 281)
at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java: 210)
at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java: 233)
at android.os.Handler.dispatchMessage(Handler.java: 102)
at android.os.Looper.loop(Looper.java: 135)
at android.app.ActivityThread.main(ActivityThread.java: 5312)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java: 372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 696)
Caused by: android.os.DeadObjectException
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(Binder.java: 496)
at com.mapzen.android.lost.internal.IFusedLocationProviderCallback$Stub$Proxy.onLocationChanged(IFusedLocationProviderCallback.java: 104)
at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(FusedLocationProviderServiceDelegate.java: 76)
at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java: 196)
at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java: 281)
at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java: 210)
at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java: 233)
at android.os.Handler.dispatchMessage(Handler.java: 102)
at android.os.Looper.loop(Looper.java: 135)
at android.app.ActivityThread.main(ActivityThread.java: 5312)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java: 372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 696)
```

cc @sarahlensing @Guardiola31337 @zugaldia

### PR DESCRIPTION
**Pull request by sarahlensing**
### Overview
This is the [first step](https://github.com/mapzen/lost/issues/229) towards improving and standardizing exception handling in Lost. Currently we catch and re-throw `RuntimeExceptions` thrown when interacting with the service, a hard stance for a library to take. To work towards giving developers the chance to handle recovering from these cases, this PR updates Lost to silently ignore `RemoteExceptions`. Future work will provide complete APIs to allow developers to handle recovering from these states as they see fit. It will potentially migrate [existing silent failures](https://github.com/mapzen/lost/blob/master/lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java#L144-L166) to use these new APIs.

Closes #218, #223

### CODE REVIEW

File: lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java [hunk 1]
```diff
@@ -123,19 +125,25 @@ public boolean isConnected() {
 
   @Override public Location getLastLocation(LostApiClient client) {
     throwIfNotConnected(client);
+    Location location = null;
     try {
-      return service.getLastLocation();
+      location = service.getLastLocation();
     } catch (RemoteException e) {
-      throw new RuntimeException(e);
+      Log.e(TAG, "Error occurred trying to get last Location " + e.getStackTrace());
```
Comment (westnordost) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: There is also Log.e(TAG,message,throwable), wouldn't this be preferrable? Or has that method any downsides I am not aware of?

File: lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java [hunk 2]
```diff
@@ -123,19 +125,25 @@ public boolean isConnected() {
...
     throwIfNotConnected(client);
+    LocationAvailability availability = null;
     try {
-      return service.getLocationAvailability();
+      availability = service.getLocationAvailability();
     } catch (RemoteException e) {
-      throw new RuntimeException(e);
+      Log.e(TAG, "Error occurred trying to get LocationAvailability " + e.getStackTrace());
+    } finally {
+      return availability;
```
Comment (westnordost) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: Will return null on error. Assuming this how Google's APIs behave as well, it would be good to mention this in the javadoc.

File: lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java (hunk 1 above)
Comment (sarahlensing) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: Updated

Comment (ecgreb) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: +1

File: lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java (hunk 2 above)
Comment (sarahlensing) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: Good catch, updated

File: lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java [hunk 3]
```diff
@@ -123,19 +125,25 @@ public boolean isConnected() {
...
     throwIfNotConnected(client);
+    Location location = null;
     try {
-      return service.getLastLocation();
+      location = service.getLastLocation();
     } catch (RemoteException e) {
-      throw new RuntimeException(e);
+      Log.e(TAG, "Error occurred trying to get last Location " + e.getStackTrace());
+    } finally {
+      return location;
```
Comment (ecgreb) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: As @westnordost pointed out below with availability, this will also return `null` if an error is encountered.

This behavior is consistent will play services.

File: lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java [hunk 4]
```diff
@@ -123,19 +125,25 @@ public boolean isConnected() {
...
     throwIfNotConnected(client);
+    Location location = null;
     try {
-      return service.getLastLocation();
+      location = service.getLastLocation();
     } catch (RemoteException e) {
-      throw new RuntimeException(e);
+      Log.e(TAG, "Error occurred trying to get last Location", e);
+    } finally {
+      return location;
```
Comment (ecgreb) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: I would just add a note in the Javadoc for `getLastLocation()` that `null` is also a valid return value here and this looks good to go.

Comment (sarahlensing) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: We do have this documented already `If a location is not available, which should happen very rarely, null will be returned.`

Comment (ecgreb) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: 👍
