### PR TITLE
Location provider enabled/disabled

### LINKED ISSUE #123: onProviderDisabled/Enabled is not working properly
- When gps provider status changed, the onProviderDisabled/Enabled is working properly.
- But when network provider  status changed, the onProviderDisabled/Enabled is not working properly。
- (I close wifi , mobile data, change to airplane mode.  the onProviderDisabled/Enabled is not work.)

### PR DESCRIPTION
**Pull request by sarahlensing**
### Overview
This PR changes the underlying mechanism that Lost uses to notify of providers enabled/disabled from a `LocationListener` to a `ContentObserver` on the system location provider setting.

### Proposed Changes
`FusionEngine` no longer does anything with its provider changed `LocationListener` methods and instead uses `LocationProviderChangedHandler` to receive notifications of providers enabled & disabled. The `LocationProviderChangedHandler` handles setting up a `ContentObserver` to listen to changes to `Settings.System.LOCATION_PROVIDERS_ALLOWED`.

Closes #123

### CODE REVIEW

File: lost/src/main/java/com/mapzen/android/lost/api/LocationListener.java [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package com.mapzen.android.lost.api;
 
 import android.location.Location;
+import android.os.Looper;
```
Comment (ecgreb) [inline lost/src/main/java/com/mapzen/android/lost/api/LocationListener.java]:
```
:lost:checkstyle[ant:checkstyle] /home/ubuntu/lost/lost/src/main/java/com/mapzen/android/lost/api/LocationListener.java:4:8: Unused import - android.os.Looper.
```

File: lost-sample/src/main/java/com/example/lost/LocationAvailabilityActivity.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+            public void onConnectionSuspended() {
+
+            }
+        }).build();
+        client.connect();
+    }
+
+    private void checkLocationAvailability() {
+        LocationAvailability availability =
+                LocationServices.FusedLocationApi.getLocationAvailability(client);
```
Comment (ecgreb) [inline lost-sample/src/main/java/com/example/lost/LocationAvailabilityActivity.java]: While exercising a call to `FusedLocationApi.getLocationAvailability(client)` is good we should also verify that `LocationCallback` is properly invoked when location updates have been requested and provider status changes occur.

https://github.com/mapzen/lost/blob/master/lost/src/main/java/com/mapzen/android/lost/api/FusedLocationProviderApi.java#L100-L101

This is the use case that would more suitably replace `LocationListener.onProviderEnabled(String provider)` and `LocationListener.onProviderDisabled(String provider)` since the client app is relying on a push style notification rather than actively polling the provider status.

File: lost/src/main/java/com/mapzen/android/lost/api/LocationListener.java [hunk 3]
```diff
@@ -17,14 +18,28 @@
   void onLocationChanged(Location location);
 
   /**
-   * Called when a location provider is disabled.
+   * Called when a location provider is disabled. You will only receive updates for the priority
```
Comment (ecgreb) [inline lost/src/main/java/com/mapzen/android/lost/api/LocationListener.java]: :+1:
