### PR TITLE
Prevent crash due to attempting to unbind service when not currently bound

### LINKED ISSUE #132: Verify service is bound before attempting to disconnect
### Description

Calling `LostApiClientImpl.disconnect()` can result in fatal crash if service is not bound.

### Steps to Reproduce

Attempt to disconnect client before fully connected.

### Lost & Android Version

Lost 2.1.1
Android 6.0.1

```
10-21 17:26:00.092 24813-24813/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.mapzen.erasermap, PID: 24813
                                                   java.lang.RuntimeException: Unable to pause activity {com.mapzen.erasermap/com.mapzen.erasermap.controller.MainActivity}: java.lang.IllegalArgumentException: Service not registered: com.mapzen.android.lost.internal.FusedLocationProviderApiImpl$2@c390cb5
                                                       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3381)
                                                       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
                                                       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:150)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.IllegalArgumentException: Service not registered: com.mapzen.android.lost.internal.FusedLocationProviderApiImpl$2@c390cb5
                                                       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1044)
                                                       at android.app.ContextImpl.unbindService(ContextImpl.java:1337)
                                                       at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
                                                       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl$1.onDisconnect(FusedLocationProviderApiImpl.java:59)
                                                       at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.disconnect(FusedLocationServiceConnectionManager.java:65)
                                                       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.disconnect(FusedLocationProviderApiImpl.java:94)
                                                       at com.mapzen.android.lost.internal.LostApiClientImpl.disconnect(LostApiClientImpl.java:53)
                                                       at com.mapzen.erasermap.model.LostClientManager.disconnect(LostClientManager.kt:55)
                                                       at com.mapzen.erasermap.controller.MainActivity.onPause(MainActivity.kt:217)
                                                       at android.app.Activity.performPause(Activity.java:6403)
                                                       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1312)
                                                       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
                                                       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340) 
                                                       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315) 
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:150) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

### PR DESCRIPTION
**Pull request by ecgreb**
### Overview

Prevent crash due to attempting to unbind service when not currently bound. Simplify logic to disconnect fused location client and service.

### Proposed Changes

* Combines the responsibilities from `LostClientManager.removeClient(LostApiClient)` and `LostClientManager.disconnect(LostApiClient)` into a single method.
* Actively track whether service is currently bound in `FusedLocationProviderApiImpl` to prevent attempts to unbind when service is not bound. Fixes `IllegalArgumentException`.
* Removes client param to `FusedLocationServiceConnectionManager.disconnect()` since it was only ever called with `null`.
* Removes `FusedLocationProviderService.disconnect(LostApiClient)` since disconnecting the client is now handled by `LostClientManager.removeClient(LostApiClient)` called before disconnecting the service.
* Adds tests for `EventCallbacks` methods in `FusedLocationProviderApiImpl`.

Closes #132

### CODE REVIEW

File: lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java [hunk 1]
```diff
@@ -26,56 +27,52 @@
...
 
-    @Override public void onServiceConnected(IBinder binder) {
-      FusedLocationProviderService.FusedLocationProviderBinder fusedBinder =
-          (FusedLocationProviderService.FusedLocationProviderBinder) binder;
-      if (fusedBinder != null) {
-        service = fusedBinder.getService();
-      }
+  @Override public void onDisconnect() {
+    if (isBound) {
+      context.unbindService(this);
```
Comment (sarahlensing) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: I think we should set `isBound = false` here. `onServiceDisconnected` is not called when the client is unbound normally. According to the docs, `onServiceDisconnected` is only called when the process hosting the service is killed/crashed.

Comment (ecgreb) [inline lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java]: Good catch. It appears our crash is coming from when two clients attempt to disconnect at the same time. Updated with the suggested change so the second one will not attempt to call `unbindService(this)`.
